version: '2.28.1'
services:
  productreview_app:
    image: 767398069045.dkr.ecr.us-east-1.amazonaws.com/product_review:1.0
    container_name: productreview_app
    ports:
      - 8000:8000
    env_file:
      - /etc/productreview_app.env
  my_nginx:
    image: 767398069045.dkr.ecr.us-east-1.amazonaws.com/custom_nginx:5.0
    container_name: custom_nginx
    ports:
      - 80:80
    depends_on:
      - productreview_app
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"
    command: [
      "-nginx.scrape-uri=http://127.0.0.1:80/metrics"
    ]
    depends_on:
      - my_nginx
    
      
