name: app_code-project02
services:
  nginx:
    depends_on:
      productreview_app:
        condition: service_started
        required: true
    image: nginx
    networks:
      default: null
    ports:
      - mode: ingress
        target: 80
        published: "80"
        protocol: tcp
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    volumes:
      - type: bind
        source: /home/adilk/Project02/App_code-Project02/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
        bind:
          create_host_path: true
  nginx-prometheus-exporter:
    command:
      - -nginx.scrape-uri
      - http://nginx:8080/stub_status
    depends_on:
      nginx:
        condition: service_started
        required: true
    environment:
      SSL_VERIFY: "false"
    image: nginx/nginx-prometheus-exporter:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 9113
        published: "9113"
        protocol: tcp
  productreview_app:
    environment:
      MYSQL_DATABASE: product_reviews
      MYSQL_HOST: localhost
      MYSQL_PASSWORD: Sql12345
      MYSQL_USER: adilk
    image: 767398069045.dkr.ecr.us-east-1.amazonaws.com/product_review:1.0
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8000
        published: "8000"
        protocol: tcp
networks:
  default:
    name: app_code-project02_default
