---

- hosts: "{{ WebServer1 }}"
  become: true
  pre_tasks:
    - name: Update and Upgrade
      tags: always
      apt:
        upgrade: dist
        update_cache: yes

  tasks:
    - name: Install mysql-client to configure db
      tags: mysql-client
      apt:
        name:
          - mysql-client
        state: latest
        update_cache: yes

    - name: create rds sql database and required table from first webserver
      tags: sql,db,rds
      command: |
         mysql -h{{ rds_endpoint }} -u{{ dbusername }} -p{{ dbpassword }} -e "CREATE DATABASE IF NOT EXISTS product_reviews; USE product_reviews; CREATE TABLE IF NOT EXISTS reviews (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), product_name VARCHAR(255), review TEXT);"


- hosts: all
  become: true
  pre_tasks:
    - name: Update and Upgrade
      tags: always
      apt:
        upgrade: dist
        update_cache: yes

  tasks:
    - name: Create environment file
      tags: environment,db
      copy:
         dest: /etc/productreview_app.env
         content: |
           MYSQL_HOST={{ rds_endpoint }}
           MYSQL_USER={{ dbusername }}
           MYSQL_PASSWORD={{ dbpassword }}
           MYSQL_DATABASE='product_reviews'
    
    - name: Install Docker
      tags: docker
      command: |
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update

    - name: Copy Docker compose file
      tags: docker,compose
      copy:
        src: ../docker-compose.yaml 
        dst: /home/ubuntu/docker-compose.yaml

    - name: Pull Docker images and docker compose up
      tags: docker,pull,images
      command: |
        docker pull {{ aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com/product_review:{{ product_review_version }}
        docker pull {{ aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com/custom_nginx:{{ custom_nginx_version }}
        docker compose up -d



    