version: '3.9'
services:
  productreview_app:
    image: 767398069045.dkr.ecr.us-east-1.amazonaws.com/product_review:1.0
    ports:
      - 8000:8000
    env_file:
      - /etc/productreview_app.env
    networks:
      - project02
    deploy:
      replicas: 2

  nginx:
    image: nginx
    #container_name: nginx
    volumes:
      - /home/ubuntu/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
      #- 8080:8080
    networks:
      - project02
    depends_on:
      - productreview_app
    deploy:
      replicas: 1
      placement:
         constraints:
           - node.role == manager

networks:
  project02:
    driver: overlay
    attachable: true