name: "Unit test and deploy to dev servers"

on:
    push:
        branches:
            - staging

env:
  PRODUCT_REVIEW_VERSION: "1.0"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ENVIRONMENT: staging

jobs:
    Tests:
        name: "Unittest_of_app_with_DB"
        runs-on: ubuntu-latest

        env:
            #These credentials are for test in runner
            MYSQL_HOST: 127.0.0.1
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: test_db
            #############################            
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Start MySql 
              run: |
                sudo service mysql start

            - name: Create DB and table
              run: |
                  mysql -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD -e "CREATE DATABASE $MYSQL_DATABASE;" 
                  mysql -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD -e "USE $MYSQL_DATABASE; CREATE TABLE reviews (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255),product_name VARCHAR(255),review TEXT);"

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.8'
  
            - name: venv activate and install dependencies
              run: |
                python3 -m venv .venv
                source .venv/bin/activate
                python3 -m pip install --upgrade pip
                pip3 install -r requirements.txt
              working-directory: ./flask_app_code

            - name: Run tests
              run: |
                source .venv/bin/activate
                pytest
                deactivate
              working-directory: ./flask_app_code


    Build_and_Push_Docker_image:
       name: "Build_and_Push_Docker_image"
       runs-on: ubuntu-latest
       needs: Tests
       steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Configure AWS credentials for ECR
          run: |
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
         
        - name: Build and push Docker images for Productreview_app to ECR
          run: |
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/product_review:$PRODUCT_REVIEW_VERSION .
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/product_review:$PRODUCT_REVIEW_VERSION
          working-directory: ./flask_app_code
          

    Server-RDS_DB-Monitoring_configs:
        name: "Ensures basic server configs,RDS mysql database,monitoring configs"
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Install Ansible,boto3 and store ssh key in runner
            run: |
              pip3 install ansible boto3
              mkdir -p /home/runner/.ssh/
              echo -e "${{ secrets.ANSIBLE_SSH_KEY }}" > /home/runner/.ssh/flask_ec2.pem
              chmod 600 ~/.ssh/flask_ec2.pem

          - name: Fetch RDS endpoint from AWS
            run: |
              rds_endpoint=$(aws rds --region us-east-1 describe-db-instances --db-instance-identifier ${ENVIRONMENT}productreviewdb --query 'DBInstances[*].Endpoint.Address' --output text) 
              echo "RDS_ENDPOINT=${rds_endpoint}" >> $GITHUB_ENV

          - name: Configure mysql rds db and docker commands in webservers
            env:
              RDS_ENDPOINT: ${{ env.RDS_ENDPOINT }}
            run: |
              ansible-playbook -i ./inventory/hosts.aws_ec2.yaml -u ${{ secrets.WEBSERVER_USER }} --private-key=/home/runner/.ssh/flask_ec2.pem main.yaml --extra-vars "env_webserver_group=tag_Groups_${ENVIRONMENT}WebServers env_webserver1=tag_Name_${ENVIRONMENT}WebServer1 rds_endpoint=$RDS_ENDPOINT dbusername=${{ secrets.DBUSERNAME }} dbpassword=${{ secrets.DBPASSWORD }} aws_account_id=$AWS_ACCOUNT_ID"
            working-directory: ./ansible_playbook

    Deploy_New_Version:
         name: "Deploy new version (App_stack and Monitoring_stack)"
         runs-on: ubuntu-latest
         needs: 
          - Build_and_Push_Docker_image
          - Server-RDS_DB-Monitoring_configs
         steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Fetch Docker swarm leader ip and set as env variable
            run: |
                swarm_leader_ip=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=${ENVIRONMENT}WebServer1" --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
                echo "SWARM_LEADER_IP=${swarm_leader_ip}" >> $GITHUB_ENV
          
          - name: Copy appstack compose file via ssh 
            env:
              SWARM_LEADER_IP: ${{ env.SWARM_LEADER_IP }}
            uses: appleboy/scp-action@v0.1.7
            with:
             host: ${{ env.SWARM_LEADER_IP }}
             username: ${{ secrets.WEBSERVER_USER }}
             key: ${{ secrets.ANSIBLE_SSH_KEY }}
             source: "app_compose_files/docker-compose-${{ env.ENVIRONMENT }}.yaml"
             target: /home/ubuntu/

          - name: Deploy docker app_stack and monitoring_stack
            env:
              SWARM_LEADER_IP: ${{ env.SWARM_LEADER_IP }}
            uses: appleboy/ssh-action@master
            with:
               host: ${{ env.SWARM_LEADER_IP }}
               username: ${{ secrets.WEBSERVER_USER }}
               key: ${{ secrets.ANSIBLE_SSH_KEY }}
               script: |
                 cd /home/ubuntu/app_compose_files/
                 sudo docker stack deploy --with-registry-auth --detach=false -c docker-compose.yaml app_stack
                 cd /home/ubuntu/monitoring_files
                 sudo docker stack deploy --with-registry-auth --detach=false -c /home/ubuntu/monitoring_files/docker-compose.yaml monitoring_stack

         