name: "Unit-testing-with-app-and-mysql"

on:
    push:
        branches:
            - feature


jobs:
    Tests:
        name: "Unittest_of_app_with_database"
        runs-on: ubuntu-latest

        env:
            MYSQL_HOST: 127.0.0.1
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: test_db

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Start MySql and create db
              run: |
                sudo service mysql start
                mysql -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD -e "CREATE DATABASE test_db; USE test_db;" 
                mysql -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD -e "CREATE TABLE reviews (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255),product_name VARCHAR(255),review TEXT);"

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.8'
  
            - name: venv activate and install dependencies
              run: |
                python3 -m venv .venv
                source .venv/bin/activate
                python3 -m pip install --upgrade pip
                pip3 install -r requirements.txt

            - name: Run tests
              run: |
                source .venv/bin/activate
                pytest
               

  




